#!/bin/bash
#
# nexus		Startup script for Nexus Repository Manager.
#
# chkconfig: 345 90 14
# description: Nexus startup script for Nexus Repository Manager
#
# This will start the nexus in Tomcat.
#
#
NEXUSLOCATION=/home/nexus/nexus-1.0.4
# Start Tomcat under a particular user.
start() {
	# This assume that JAVA_HOME is set for the user.
	su -l nexus $NEXUSLOCATION/bin/startup.sh
}

stop() {
	su -l nexus $NEXUSLOCATION/bin/shutdown.sh
}
#
# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  reload)
        reload
    ;;
  *)
    echo $"Usage: $prog {start|stop|restart}"
    exit 1
esac
exit 0;

